'use client';

import './globals.css';
import { Nunito_Sans } from 'next/font/google';
import { cn } from '@/lib/utils';

const nunitoSans = Nunito_Sans({ subsets: ['latin'], variable: '--font-sans' });

export const metadata = {
  title: 'Welcome to Vulcan',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cn('font-sans', nunitoSans.variable)}>
      <body>{children}</body>
    </html>
  );
}
