'use client';

import './globals.css';
import { Nunito_Sans } from 'next/font/google';
import { cn } from '@/lib/utils';
import { StoreProvider } from '@/modules/store';

const nunitoSans = Nunito_Sans({ subsets: ['latin'], variable: '--font-sans' });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cn('font-sans', nunitoSans.variable)}>
      <title>Welcome to Vulcan</title>
      <meta name="description" content="Generated by create-nx-workspace" />
      <body>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
