'use client';

import { AppSidebar } from '@/components/app-sidebar';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import { TooltipProvider } from '@/components/ui/tooltip';
import { cn } from '@/lib/utils';
import { StoreProvider } from '@/modules/store';
import { Nunito_Sans } from 'next/font/google';
import './globals.css';

const nunitoSans = Nunito_Sans({ subsets: ['latin'], variable: '--font-sans' });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cn('font-sans', nunitoSans.variable)}>
      <title>Welcome to Vulcan</title>
      <meta name="description" content="Generated by create-nx-workspace" />
      <body>
        <StoreProvider>
          <TooltipProvider>
            <SidebarProvider className="h-svh overflow-hidden">
              <AppSidebar />
              <SidebarInset className="overflow-y-auto px-2 py-4">
                {children}
              </SidebarInset>
            </SidebarProvider>
          </TooltipProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
